# Generated by Django 4.1.7 on 2023-02-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('rank', models.IntegerField(verbose_name='排名')),
                ('name', models.CharField(default='', max_length=200, verbose_name='名称')),
                ('link', models.CharField(default='', max_length=200, verbose_name='链接')),
                ('star', models.CharField(default='', max_length=200, verbose_name='星级')),
                ('grade', models.CharField(default='', max_length=200, verbose_name='评分')),
                ('numOfGrade', models.CharField(default='', max_length=200, verbose_name='评价人数')),
                ('photo', models.CharField(default='', max_length=200, verbose_name='封面图')),
                ('person', models.CharField(default='', max_length=200, verbose_name='导演')),
                ('year', models.CharField(default='', max_length=200, verbose_name='年份')),
            ],
            options={
                'verbose_name_plural': '电影列表',
                'db_table': 'Films',
            },
        ),
    ]
