# Generated by Django 4.1.7 on 2023-03-04 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_users_options_alter_users_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='start',
            options={'verbose_name': '收藏', 'verbose_name_plural': '收藏'},
        ),
        migrations.AlterModelTable(
            name='start',
            table='Star',
        ),
    ]
