# Generated by Django 4.1.7 on 2023-03-04 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_start_options_alter_start_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='start',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.users', verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='start',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.films', verbose_name='电影'),
        ),
    ]
