# Generated by Django 4.1.7 on 2023-03-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_start_user_alter_start_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(default='', max_length=120, verbose_name='手机号'),
        ),
    ]
